# Generated by Django 3.1.2 on 2020-10-30 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201029_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('V', 'Visual'), ('L', 'Logical'), ('O', 'Other')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
