# Generated by Django 3.1.2 on 2020-11-01 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_bug_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
