# Generated by Django 3.1.2 on 2020-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201102_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
    ]
