# Generated by Django 3.1.2 on 2020-11-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201102_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bug_pics'),
        ),
    ]
