# Generated by Django 3.1.2 on 2020-11-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20201102_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='bug',
            name='image2',
            field=models.ImageField(default='default_bug.png', upload_to='bug_pics'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='image',
            field=models.ImageField(default='default_bug.png', upload_to='bug_pics'),
        ),
    ]
